### ISSUE TITLE
Separar css em componentes

### ISSUE THREAD

**Issue by cristianpdev** [cristianpdev/the-mandalorian-page.github.io#4]
## Solicitação:
Separar estilos CSS de cada componente HTML em um arquivo.
Ex. para o componente Header criar arquivo `header.css`

## Como fazer:
- Arquivos de exemplo:
```css
/* css/components/header.css */
header {
    background-color: #000;
    color: #fff;
}
header .item {
    display: flex;
}
```

```css
/* css/components/footer.css */

footer {
    display: inline-flex;
    justify-content: center;
}
```
## Por que fazer?
- Melhor para organização e manutenção dos componentes
- Evitar arquivos `css` com centenas de linhas
